---
#
# Sample raw UCI configuration extras, needed for the MikroTik RB750Gr3.
# Note there's no actual MIPS machine in this demo, this is only an example usage
# of these options.
#
dlan_uci_system_extras: |
  config gpio_switch 'poe_passthrough'
          option name 'PoE Passthrough'
          option gpio_pin '17'
          option value '0'
dlan_uci_network_extras: |
  config switch
          option name 'switch0'
          option reset '1'
          option enable_vlan '1'

  config switch_vlan
          option device 'switch0'
          option vlan '1'
          option ports '1 2 3 4 6t'

  config switch_vlan
          option device 'switch0'
          option vlan '2'
          option ports '0 6t'
